### PR TITLE
FIX: Replaces dynamically sized structures with static for keypair

### LINKED ISSUE #2: Remove usage of structures with dynamical size.
If you know the length and it is immutable, why use Vec?

_Originally posted by @takemiyamakoto in https://github.com/soramitsu/ursa_key_utils/pull/1_

### PR DESCRIPTION
**Pull request by e-ivkov**
Wrapped arrays into structs, as it was needed to implement conversions for them and they also have different sizes.

### CODE REVIEW

**Comment by humb1t** [comment]
@eadventurous small hint for naming of PR.
It's better to use `[FIX|FEATURE]: Short description` in title and paste `/closes #issue_number` in comment. That way Github will link PR with an issue and reviewer will be able to understand PR intention from a list of PR.

**Comment by humb1t** [comment]
I also recommend to keep as a rule that Pull Request should contain only one commit. 
No merge commits (use rebase) and no squashing, better to force push upfront.
Master branch will be in a form of a beautiful short line.

File: src/lib.rs [hunk 1]
```diff
@@ -1,37 +1,116 @@
+use std::convert::TryFrom;
+use std::fmt::{Display, Error, Formatter};
```
Comment (humb1t) [inline src/lib.rs]: Can we compact them into 
```rust
use std::{convert::TryFrom, fmt::{Display, Error, Formatter}};
```
Why I think it's better - it's easier to keep dependencies with common roots together. Bad case:
```rust
use std::convert::TryFrom;
....
user ursa::...
...
use std::convert::TryFrom;
...
use std::...
```

File: src/lib.rs [hunk 2]
```diff
@@ -1,37 +1,116 @@
...
+    }
+}
+
+impl TryFrom<Vec<u8>> for Sha512PublicKey {
+    type Error = String;
+
+    fn try_from(v: Vec<u8>) -> Result<Self, Self::Error> {
+        if v.len() == PUBLIC_KEY_LENGTH {
+            let mut arr = [0u8; PUBLIC_KEY_LENGTH];
+            for (place, element) in arr.iter_mut().zip(v.iter()) {
```
Comment (humb1t) [inline src/lib.rs]: how about generic [impl](https://doc.rust-lang.org/src/core/array/mod.rs.html#135-145):
```
impl<T, const N: usize> TryFrom<&[T]> for [T; N]
```
Should be good for us - to call it and map Result.

File: src/lib.rs [hunk 3]
```diff
@@ -1,37 +1,116 @@
...
+    }
+}
+
+impl TryFrom<Vec<u8>> for Sha512PrivateKey {
+    type Error = String;
+
+    fn try_from(v: Vec<u8>) -> Result<Self, Self::Error> {
+        if v.len() == PRIVATE_KEY_LENGTH {
+            let mut arr = [0u8; PRIVATE_KEY_LENGTH];
+            for (place, element) in arr.iter_mut().zip(v.iter()) {
```
Comment (humb1t) [inline src/lib.rs]: The same as for public

File: src/lib.rs [hunk 4]
```diff
@@ -1,37 +1,116 @@
...
+impl From<&Sha512PublicKey> for Vec<u8> {
+    fn from(key: &Sha512PublicKey) -> Self {
+        key.0.to_vec()
+    }
+}
+
+impl TryFrom<Vec<u8>> for Sha512PublicKey {
+    type Error = String;
+
+    fn try_from(v: Vec<u8>) -> Result<Self, Self::Error> {
```
Comment (humb1t) [inline src/lib.rs]: IMHO better to use full names - like `vector`.

File: src/lib.rs [hunk 5]
```diff
@@ -1,37 +1,116 @@
...
+        if v.len() == PUBLIC_KEY_LENGTH {
+            let mut arr = [0u8; PUBLIC_KEY_LENGTH];
```
Comment (humb1t) [inline src/lib.rs]: array

File: src/lib.rs [hunk 6]
```diff
@@ -1,37 +1,116 @@
...
 /// [OsRng](https://docs.rs/rand/0.7/rand/rngs/struct.OsRng.html) random number generator is used.
-pub fn generate_keypair() -> Result<(Vec<u8>, Vec<u8>), String> {
+pub fn generate_keypair() -> Result<(Sha512PublicKey, Sha512PrivateKey), String> {
     match Ed25519Sha512.keypair(Option::None) {
-        Ok((public_key, private_key)) => Ok((public_key.0.clone(), private_key.0.clone())),
+        Ok((public_key, private_key)) => {
+            let public_key = Sha512PublicKey::try_from(public_key.0.clone()).unwrap();
+            let private_key = Sha512PrivateKey::try_from(private_key.0.clone()).unwrap();
+            Ok((public_key, private_key))
+        }
```
Comment (humb1t) [inline src/lib.rs]: Let's clean it up.
1. Do we really need temporary variables with confusing names? If we need them, let's rename to sha_512_public/private_key.
2. Do not use unwrap and punish me if you see when I use it (maybe only tests should be an excuse). It will fail in runtime and without a good error message. At least `expect` should be used, but better to propagate via `?` or match result.
3. Maybe instead of `public_key.0.clone()` we should use something like `&public_key.0` now? What do you think?

File: src/lib.rs [hunk 7]
```diff
@@ -1,37 +1,116 @@
...
+pub fn generate_keypair_with_seed(
+    seed: Vec<u8>,
+) -> Result<(Sha512PublicKey, Sha512PrivateKey), String> {
     match Ed25519Sha512.keypair(Option::Some(KeyGenOption::UseSeed(seed))) {
-        Ok((public_key, private_key)) => Ok((public_key.0.clone(), private_key.0.clone())),
+        Ok((public_key, private_key)) => {
+            let public_key = Sha512PublicKey::try_from(public_key.0.clone()).unwrap();
+            let private_key = Sha512PrivateKey::try_from(private_key.0.clone()).unwrap();
+            Ok((public_key, private_key))
+        }
```
Comment (humb1t) [inline src/lib.rs]: The same as `generate_keypair`.

File: src/lib.rs [hunk 8]
```diff
@@ -1,37 +1,116 @@
...
+) -> Result<(Sha512PublicKey, Sha512PrivateKey), String> {
     match Ed25519Sha512.keypair(Option::Some(KeyGenOption::FromSecretKey(PrivateKey(
         secret_key,
     )))) {
-        Ok((public_key, private_key)) => Ok((public_key.0.clone(), private_key.0.clone())),
+        Ok((public_key, private_key)) => {
+            let public_key = Sha512PublicKey::try_from(public_key.0.clone()).unwrap();
+            let private_key = Sha512PrivateKey::try_from(private_key.0.clone()).unwrap();
+            Ok((public_key, private_key))
+        }
```
Comment (humb1t) [inline src/lib.rs]: The same as above

File: src/main.rs [hunk 9]
```diff
@@ -10,35 +10,35 @@ fn main() {
...
+                .takes_value(true)
         )
         .get_matches();
     let seed_option = matches.value_of("seed");
     let secret_option = matches.value_of("secret");
     if let Some(seed) = seed_option {
         let (public_key, private_key) = generate_keypair_with_seed(seed.as_bytes().into()).unwrap();
-        println!("Public key: {:?}", &public_key);
-        println!("Private key: {:?}", &private_key);
+        println!("Public key: {:?}", &Vec::from(&public_key));
```
Comment (humb1t) [inline src/main.rs]: Let's implement Display for `Sha512PrivateKey` and `Sha512PublicKey`

**Review by humb1t — CHANGES_REQUESTED** [review]

**Comment by takemiyamakoto** [comment]
> I also recommend to keep as a rule that Pull Request should contain only one commit.
> No merge commits (use rebase) and no squashing, better to force push upfront.
> Master branch will be in a form of a beautiful short line.

I'm not totally convinced by this. Sometimes splitting up actions into multiple commits can improve understandability of the programmer's thoughts. We should probably discuss this some more.

**Comment by humb1t** [comment]
> I'm not totally convinced by this. Sometimes splitting up actions into multiple commits can improve understandability of the programmer's thoughts. We should probably discuss this some more.

My point is to do not spend time on another programmers thoughts. If they really important, he or she or it should place their thoughts into tests, docs or `CHANGELOG.md`. It's still be possible to look into forced commits in PR history in case of some incident investigation or a law suit =)

File: src/lib.rs (hunk 3 above)
Comment (gsomix) [reply src/lib.rs]: Nope. `TryFrom` is implemented for fixed-size arrays with length _up to 32 elements_. `PRIVATE_KEY_LENGTH` is 64.

Comment (humb1t) [reply src/lib.rs]: image
Sad but true

File: src/lib.rs (hunk 2 above)
Comment (e-ivkov) [reply src/lib.rs]: To my understanding const generics are still in nightly as of [RFC 2000 tracking issue](https://github.com/rust-lang/rust/issues/44580). Correct me if I am wrong.

File: src/lib.rs (hunk 6 above)
Comment (e-ivkov) [reply src/lib.rs]: The reason I used `unwrap` there is that we rely on the underlying library to have exact sizes, and it would be reasonable to panic otherwise. 

But maybe yes, we can propagate the error.

**Comment by e-ivkov** [comment]
> I also recommend to keep as a rule that Pull Request should contain only one commit.
> No merge commits (use rebase) and no squashing, better to force push upfront.
> Master branch will be in a form of a beautiful short line.

@humb1t You mean something like [this policy](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)? Maybe we should also add it to our wiki if we accept it.

**Comment by humb1t** [comment]
@eadventurous I mean [Centralized Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows#centralized-workflow) without squashes.

File: src/lib.rs (hunk 2 above)
Comment (humb1t) [reply src/lib.rs]: We don't need to implement our own. Can we use already landed stable realization for [u8; 32]?

File: src/lib.rs (hunk 6 above)
Comment (humb1t) [reply src/lib.rs]: Maybe it's okay to panic, but please use `expect` in this case with a good panic message.

**Review by humb1t — APPROVED** [review]
